class Const(object):
    CONST_ZERO = 0
    CONST_ONE = 1
    CONST_TWO = 2
    CONST_THREE = 3
    CONST_FOUR = 4
    CONST_FIVE = 5
    CONST_SIX = 6
    CONST_SEVEN = 7
    CONST_EIGHT = 8
    CONST_NINE = 9
    CONST_TEN = 10
    CONST_TWELVE = 12
    CONST_THIRTY_ONE = 31