# Generated by Django 3.2.9 on 2021-11-29 21:12

from django.db import migrations, models
import taxfree.validation


class Migration(migrations.Migration):

    dependencies = [
        ('taxfree', '0002_alter_tax_free_vat_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_free',
            name='vat_code',
            field=models.CharField(db_index=True, max_length=13, unique=True, validators=[taxfree.validation.Validation.check_vat_code], verbose_name='vat_code'),
        ),
    ]
