# Generated by Django 3.2.9 on 2021-12-08 11:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxfree', '0003_alter_tax_free_vat_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tax_free',
            name='company',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z]*$', 'Only letters.')], verbose_name='company'),
        ),
    ]
